# Generated by Django 5.2.6 on 2025-11-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_alumnos_options_alumnos_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='carerra',
            new_name='carrera',
        ),
    ]
